#!/usr/bin/env python3
"""Write the laws:code skill and its rung projections from plugins/laws/source/code/.

Run: python3 plugins/laws/source/generate.py          # write the outputs
     python3 plugins/laws/source/generate.py --check  # exit 1 if an output is stale or over budget

Outputs, under plugins/laws/skills/code/:

  SKILL.md               every law at the rung profiles/default.toml gives it
  references/rung-s.md   every law at S
  references/rung-m.md   every law at M

skeleton.md fixes the order. Each of its `<!-- include: <file> -->` lines is replaced by
that file verbatim; every other skeleton line is copied as is. Inside the included files:

  <!-- rung: S -->         marks the one paragraph that follows it as serving rung S
  <!-- rung: M -->         ... as serving rung M; unmarked text is L
  <!-- law-index -->       the law tokens, derived from the law headings, in document order
  <!-- framing-index -->   the framing tokens, likewise
  <!-- generated-notice --> the line saying this output is generated, and from what; it sits
                           in the frontmatter as a YAML comment, so it costs the model nothing

Every file under laws/ is a law and every file under framings/ a framing: its first line is
`## [LAW:<file stem>] - ...` (or FRAMING), and the skeleton includes each one exactly once.

A law rendered at L is its source verbatim. At S it is its heading and its S-marked
paragraphs; at M, its heading and its S- and M-marked paragraphs; always in source order.
So S is a subset of M and M of L by construction. Rendering removes the rung lines and
nothing else, and the text outside the laws is the same at every rung.

A profile (profiles/<name>.toml) names the model its budget is counted on, the budget in
tokens, and a rung for every law. counts.json records each output's token count against a
hash of its text; count.py writes it, since counting needs Anthropic's API and a
credential. --check refuses an output whose recorded count is not for its current text,
and SKILL.md when its count exceeds the default profile's budget.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

HERE = Path(__file__).resolve().parent
SOURCE = HERE / "code"
SKILL_DIR = HERE.parent / "skills" / "code"
COUNTS = HERE / "counts.json"
DEFAULT_PROFILE = "default"

GENERATED = (
    "Generated by plugins/laws/source/generate.py from plugins/laws/source/code/."
    " Edit the sources and regenerate; never edit this file."
)
NOTICE = f"# {GENERATED}\n"
INDEX_WIDTH = 84

# Every single-line HTML comment in a source is one of these; anything else is a typo
# that would otherwise ship as visible text in the skill.
DIRECTIVE = re.compile(r"^<!-- (include|rung|law-index|framing-index|generated-notice)(?:: (\S+))? -->$")
SINGLE_LINE_COMMENT = re.compile(r"^<!--.*-->$")
KIND_BY_DIR = {"laws": "LAW", "framings": "FRAMING"}
Rung = Literal["S", "M", "L"]
LADDER: tuple[Rung, ...] = ("S", "M", "L")  # each rung shows its own paragraphs and those of every rung before it
RUNGS = LADDER[:-1]  # the rungs a marker can name; unmarked text is the top rung


class SourceError(Exception):
    pass


@dataclass(frozen=True)
class Unit:
    kind: str  # "LAW" or "FRAMING"
    token: str
    marks: dict[str, int]  # rung -> paragraphs marked with it


def directive(line: str, where: str) -> tuple[str, str | None] | None:
    text = line.rstrip("\n")
    m = DIRECTIVE.match(text)
    if m:
        return m.group(1), m.group(2)
    if SINGLE_LINE_COMMENT.match(text.strip()):
        raise SourceError(f"{where}: unknown directive {text!r}")
    return None


def marked_paragraphs(lines: list[str], where: str) -> dict[str, list[str]]:
    """Rung -> first line of each paragraph marked with it."""
    marked: dict[str, list[str]] = {rung: [] for rung in RUNGS}
    for i, line in enumerate(lines):
        d = directive(line, f"{where}:{i + 1}")
        if d is None or d[0] != "rung":
            continue
        rung = d[1]
        if rung not in RUNGS:
            raise SourceError(f"{where}:{i + 1}: rung must be one of {RUNGS}, got {rung!r}")
        if i > 0 and lines[i - 1].strip():
            raise SourceError(f"{where}:{i + 1}: rung marker sits inside a paragraph; it belongs on the blank line before one")
        following = lines[i + 1] if i + 1 < len(lines) else ""
        if not following.strip() or directive(following, f"{where}:{i + 2}"):
            raise SourceError(f"{where}:{i + 1}: rung marker is not followed by a paragraph")
        marked[rung].append(following)
    return marked


def read_unit(path: Path, kind: str, lines: list[str]) -> Unit:
    heading = f"## [{kind}:{path.stem}] - "
    first = lines[0].rstrip("\n") if lines else ""
    if not first.startswith(heading):
        raise SourceError(f"{path}:1: a {kind} file named {path.stem!r} opens with {heading!r}..., not {first!r}")
    marked = marked_paragraphs(lines, str(path))
    unit = Unit(kind=kind, token=path.stem, marks={rung: len(marked[rung]) for rung in RUNGS})
    if kind == "FRAMING":
        if any(marked.values()):
            raise SourceError(f"{path}: rung markers belong to laws; framing {unit.token!r} has some")
        return unit
    body = [line for line in lines[1:] if line.strip()]
    if len(body) < 2 or directive(body[0], str(path)) != ("rung", "S") or not body[1].startswith("**"):
        raise SourceError(f"law {unit.token!r} ({path}): the paragraph under the heading is not an S-marked bold statement")
    if not any(first.startswith("Diagnostic:") for first in marked["S"]):
        raise SourceError(f"law {unit.token!r} ({path}): no S-marked Diagnostic line")
    return unit


def project(lines: list[tuple[str, str]], rung: Rung) -> list[tuple[str, str]]:
    """A law's (line, where) pairs at rung: verbatim at L; below it, the heading and the
    paragraphs marked with a rung the rung shows, each kept with its marker so rendering
    treats them alike."""
    if rung == LADDER[-1]:
        return lines
    shown = LADDER[:LADDER.index(rung) + 1]
    out = [lines[0]]
    i = 1
    while i < len(lines):
        d = directive(*lines[i])
        if d is not None and d[0] == "rung" and d[1] in shown:
            end = i + 1
            while end < len(lines) and lines[end][0].strip():
                end += 1
            out += [("\n", lines[i][1]), *lines[i:end]]
            i = end
        else:
            i += 1
    return out


@dataclass(frozen=True)
class Profile:
    name: str
    model: str
    budget: int
    rungs: dict[str, Rung]


def load_profile(path: Path) -> Profile:
    try:
        data = tomllib.loads(path.read_text())
    except tomllib.TOMLDecodeError as e:
        raise SourceError(f"{path}: {e}") from e
    if set(data) != {"model", "budget", "rungs"}:
        raise SourceError(f"{path}: a profile has exactly model, budget and [rungs]; got {sorted(data)}")
    model, budget, rungs = data["model"], data["budget"], data["rungs"]
    if not isinstance(model, str) or not model:
        raise SourceError(f"{path}: model must name the model the budget is counted on")
    if not isinstance(budget, int) or isinstance(budget, bool) or budget <= 0:
        raise SourceError(f"{path}: budget must be a positive number of tokens, got {budget!r}")
    if not isinstance(rungs, dict):
        raise SourceError(f"{path}: rungs must be a table of law = rung")
    bad = {law: rung for law, rung in rungs.items() if rung not in LADDER}
    if bad:
        raise SourceError(f"{path}: rungs must be one of {LADDER}; got {bad}")
    return Profile(name=path.stem, model=model, budget=budget, rungs=rungs)


def uniform(rung: Rung, laws: list[str]) -> dict[str, Rung]:
    return {law: rung for law in laws}


def wrap_index(items: list[str]) -> list[str]:
    rows: list[list[str]] = [[]]
    for item in items:
        if rows[-1] and len(" · ".join(rows[-1] + [item]) + " ·") > INDEX_WIDTH:
            rows.append([])
        rows[-1].append(item)
    return [" · ".join(row) + (" ·" if i < len(rows) - 1 else "") + "\n" for i, row in enumerate(rows)]


@dataclass(frozen=True)
class Piece:
    lines: list[tuple[str, str]]  # (line, where it came from)
    law: str | None  # the law whose file this is, or None for any other text


@dataclass(frozen=True)
class Source:
    """The sources, read and checked once; render() lays them out at any rungs."""

    pieces: list[Piece]
    units: list[Unit]
    expanded: dict[str, list[str]]  # non-rung directive -> the lines it becomes

    @property
    def laws(self) -> list[str]:
        return [u.token for u in self.units if u.kind == "LAW"]

    def report(self) -> str:
        laws = [u for u in self.units if u.kind == "LAW"]
        marks = " ".join(f"{r}={sum(u.marks[r] for u in laws)}" for r in RUNGS)
        return f"{len(laws)} laws, {len(self.units) - len(laws)} framings, marked paragraphs {marks}"

    def render(self, rungs: dict[str, Rung], where: str) -> str:
        if set(rungs) != set(self.laws):
            missing = [law for law in self.laws if law not in rungs]
            unknown = sorted(set(rungs) - set(self.laws))
            raise SourceError(f"{where}: rungs must name every law once; missing {missing}, unknown {unknown}")
        out: list[str] = []
        for piece in self.pieces:
            lines = piece.lines if piece.law is None else project(piece.lines, rungs[piece.law])
            for line, at in lines:
                d = directive(line, at)
                if d is None:
                    out.append(line)
                elif d[0] == "include":
                    raise SourceError(f"{at}: includes do not nest")
                elif d[0] != "rung":
                    out.extend(self.expanded[d[0]])
        return "".join(out)


def read_source(source: Path = SOURCE) -> Source:
    skeleton = (source / "skeleton.md").read_text().splitlines(keepends=True)
    pieces: list[Piece] = []
    units: list[Unit] = []
    included: set[str] = set()  # laws/ and framings/ files, as the skeleton names them
    for n, line in enumerate(skeleton, 1):
        d = directive(line, f"skeleton.md:{n}")
        if d is None:
            pieces.append(Piece(lines=[(line, f"skeleton.md:{n}")], law=None))
            continue
        if d[0] != "include":
            raise SourceError(f"skeleton.md:{n}: only include lines belong in the skeleton")
        if d[1] is None:
            raise SourceError(f"skeleton.md:{n}: include names no file")
        path = source / d[1]
        if not path.is_file():
            raise SourceError(f"skeleton.md:{n}: included file {d[1]!r} does not exist")
        lines = path.read_text().splitlines(keepends=True)
        parts = Path(d[1]).parts
        kind = KIND_BY_DIR.get(parts[0]) if len(parts) > 1 else None
        law = None
        if kind is None:
            marked_paragraphs(lines, d[1])
        elif len(parts) != 2:
            raise SourceError(f"skeleton.md:{n}: {d[1]!r} is nested; {parts[0]}/ files sit directly in it")
        else:
            unit = read_unit(path, kind, lines)
            units.append(unit)
            included.add(d[1])
            law = unit.token if kind == "LAW" else None
        pieces.append(Piece(lines=[(l, f"{d[1]}:{i}") for i, l in enumerate(lines, 1)], law=law))

    tokens = {kind: [u.token for u in units if u.kind == kind] for kind in ("LAW", "FRAMING")}
    for kind, found in tokens.items():
        if len(set(found)) != len(found):
            raise SourceError(f"duplicate {kind} token in skeleton: {found}")
    for directory in KIND_BY_DIR:
        orphans = sorted({p.relative_to(source).as_posix() for p in (source / directory).rglob("*.md")} - included)
        if orphans:
            raise SourceError(f"skeleton.md includes no line for {directory}/ files: {orphans}")
    expanded = {
        "law-index": wrap_index([f"`{t}`" for t in tokens["LAW"]]),
        "framing-index": wrap_index([f"`[FRAMING:{t}]`" for t in tokens["FRAMING"]]),
        "generated-notice": [NOTICE],
    }
    return Source(pieces=pieces, units=units, expanded=expanded)


def as_reference(skill: str, rung: Rung) -> str:
    """A projection read by path is not a skill: its frontmatter goes, a one-line notice
    takes its place."""
    if not skill.startswith("---\n"):
        raise SourceError("the rendered skill does not open with frontmatter")
    body = skill[skill.index("\n---\n", 3) + len("\n---\n"):].lstrip("\n")
    return (
        f"<!-- {GENERATED} A projection of SKILL.md: every law at rung {rung}, its other paragraphs"
        f" left out; the text outside the laws is SKILL.md's. -->\n\n{body}"
    )


@dataclass(frozen=True)
class Output:
    path: str  # under the skill directory
    text: str


@dataclass(frozen=True)
class Build:
    source: Source
    profile: Profile
    outputs: list[Output]


def build(source_dir: Path = SOURCE) -> Build:
    source = read_source(source_dir)
    profile_path = source_dir / "profiles" / f"{DEFAULT_PROFILE}.toml"
    profile = load_profile(profile_path)
    projection = {rung: source.render(uniform(rung, source.laws), f"all-{rung}") for rung in ("S", "M")}
    return Build(source=source, profile=profile, outputs=[
        Output("SKILL.md", source.render(profile.rungs, str(profile_path))),
        Output("references/rung-s.md", as_reference(projection["S"], "S")),
        Output("references/rung-m.md", as_reference(projection["M"], "M")),
    ])


def sha256(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()


def read_counts(path: Path) -> dict[str, dict]:
    return json.loads(path.read_text()) if path.is_file() else {}


def count_problems(built: Build, counts: dict[str, dict]) -> list[str]:
    """Why the recorded token counts cannot be trusted for these outputs, or SKILL.md is over
    budget; empty when neither."""
    current = {
        output.path: counts[output.path] for output in built.outputs
        if output.path in counts and counts[output.path]["sha256"] == sha256(output.text)
        and counts[output.path]["model"] == built.profile.model
    }
    problems = [
        f"{output.path}: no token count for its current text on {built.profile.model}; run count.py"
        for output in built.outputs if output.path not in current
    ]
    skill = current.get("SKILL.md")
    if skill is not None and skill["tokens"] > built.profile.budget:
        problems.append(
            f"SKILL.md is {skill['tokens'] - built.profile.budget} tokens over the {built.profile.name} profile's"
            f" budget: {skill['tokens']} counted on {built.profile.model}, budget {built.profile.budget}"
        )
    return problems


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if an output is stale or over budget")
    parser.add_argument("--source", type=Path, default=SOURCE)
    parser.add_argument("--skill-dir", type=Path, default=SKILL_DIR)
    parser.add_argument("--counts", type=Path, default=COUNTS)
    args = parser.parse_args(argv)
    try:
        built = build(args.source)
    except SourceError as e:
        print(f"generate: {e}", file=sys.stderr)
        return 2
    stale = [o for o in built.outputs if not ((args.skill_dir / o.path).is_file() and (args.skill_dir / o.path).read_text() == o.text)]
    if args.check:
        for output in stale:
            print(f"generate: {args.skill_dir / output.path} is stale against {args.source}; run {Path(__file__).name}", file=sys.stderr)
    else:
        for output in stale:
            (args.skill_dir / output.path).parent.mkdir(parents=True, exist_ok=True)
            (args.skill_dir / output.path).write_text(output.text)
        written = ", ".join(o.path for o in stale) or "nothing"
        print(f"generate: wrote {written} in {args.skill_dir}: {built.source.report()}")
    problems = count_problems(built, read_counts(args.counts))
    for problem in problems:
        print(f"generate: {problem}", file=sys.stderr)
    if (args.check and stale) or problems:
        return 1
    if args.check:
        print(f"generate: {args.skill_dir} is current: {built.source.report()}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
