#!/usr/bin/env python3
"""Write plugins/laws/skills/code/SKILL.md from its sources in plugins/laws/source/code/.

Run: python3 plugins/laws/source/generate.py          # write the skill
     python3 plugins/laws/source/generate.py --check  # exit 1 if the committed skill is stale

skeleton.md fixes the order. Each of its `<!-- include: <file> -->` lines is replaced by
that file verbatim; every other skeleton line is copied as is. Inside the included files:

  <!-- rung: S -->         marks the one paragraph that follows it as serving rung S
  <!-- rung: M -->         ... as serving rung M; unmarked text is L
  <!-- law-index -->       the law tokens, derived from the law headings, in document order
  <!-- framing-index -->   the framing tokens, likewise
  <!-- generated-notice --> the line saying this output is generated, and from what

Rendering removes the rung lines and nothing else: the output is the sources verbatim, so
the all-L document is the prose an author wrote whole, never a reassembly of fields.
"""
from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCE = HERE / "code"
TARGET = HERE.parent / "skills" / "code" / "SKILL.md"

NOTICE = (
    "<!-- Generated by plugins/laws/source/generate.py from plugins/laws/source/code/."
    " Edit the sources and regenerate; never edit this file. -->\n"
)
INDEX_WIDTH = 84

# Every single-line HTML comment in a source is one of these; anything else is a typo
# that would otherwise ship as visible text in the skill.
DIRECTIVE = re.compile(r"^<!-- (include|rung|law-index|framing-index|generated-notice)(?:: (\S+))? -->$")
SINGLE_LINE_COMMENT = re.compile(r"^<!--.*-->$")
UNIT_HEADING = re.compile(r"^## \[(LAW|FRAMING):([a-z-]+)\] - ")
RUNGS = ("S", "M")


class SourceError(Exception):
    pass


@dataclass(frozen=True)
class Unit:
    kind: str  # "LAW" or "FRAMING"
    token: str


def directive(line: str, where: str) -> tuple[str, str | None] | None:
    text = line.rstrip("\n")
    m = DIRECTIVE.match(text)
    if m:
        return m.group(1), m.group(2)
    if SINGLE_LINE_COMMENT.match(text):
        raise SourceError(f"{where}: unknown directive {text!r}")
    return None


def marked_paragraphs(lines: list[str], where: str) -> dict[str, list[str]]:
    """Rung -> first line of each paragraph marked with it."""
    marked: dict[str, list[str]] = {rung: [] for rung in RUNGS}
    for i, line in enumerate(lines):
        d = directive(line, f"{where}:{i + 1}")
        if d is None or d[0] != "rung":
            continue
        rung = d[1]
        if rung not in RUNGS:
            raise SourceError(f"{where}:{i + 1}: rung must be one of {RUNGS}, got {rung!r}")
        following = lines[i + 1] if i + 1 < len(lines) else ""
        if not following.strip() or directive(following, f"{where}:{i + 2}"):
            raise SourceError(f"{where}:{i + 1}: rung marker is not followed by a paragraph")
        marked[rung].append(following)
    return marked


def read_unit(path: Path, lines: list[str]) -> Unit | None:
    m = UNIT_HEADING.match(lines[0]) if lines else None
    if m is None:
        return None
    unit = Unit(kind=m.group(1), token=m.group(2))
    if path.stem != unit.token:
        raise SourceError(f"{path}: file is named {path.stem!r} but its heading is {unit.token!r}")
    marked = marked_paragraphs(lines, str(path))
    if unit.kind == "FRAMING":
        if any(marked.values()):
            raise SourceError(f"{path}: rung markers belong to laws; framing {unit.token!r} has some")
        return unit
    s = marked["S"]
    if not any(first.startswith("**") for first in s):
        raise SourceError(f"law {unit.token!r} ({path}): no S-marked bold statement")
    if not any(first.startswith("Diagnostic:") for first in s):
        raise SourceError(f"law {unit.token!r} ({path}): no S-marked Diagnostic line")
    return unit


def wrap_index(items: list[str]) -> list[str]:
    rows: list[list[str]] = [[]]
    for item in items:
        if rows[-1] and len(" · ".join(rows[-1] + [item]) + " ·") > INDEX_WIDTH:
            rows.append([])
        rows[-1].append(item)
    return [" · ".join(row) + (" ·" if i < len(rows) - 1 else "") + "\n" for i, row in enumerate(rows)]


def render(source: Path = SOURCE) -> str:
    skeleton = (source / "skeleton.md").read_text().splitlines(keepends=True)
    assembled: list[tuple[str, str]] = []  # (line, where it came from)
    units: list[Unit] = []
    for n, line in enumerate(skeleton, 1):
        d = directive(line, f"skeleton.md:{n}")
        if d is None:
            assembled.append((line, f"skeleton.md:{n}"))
            continue
        if d[0] != "include":
            raise SourceError(f"skeleton.md:{n}: only include lines belong in the skeleton")
        path = source / d[1]
        lines = path.read_text().splitlines(keepends=True)
        unit = read_unit(path, lines)
        if unit is not None:
            units.append(unit)
        assembled.extend((l, f"{d[1]}:{i}") for i, l in enumerate(lines, 1))

    tokens = {kind: [u.token for u in units if u.kind == kind] for kind in ("LAW", "FRAMING")}
    for kind, found in tokens.items():
        if len(set(found)) != len(found):
            raise SourceError(f"duplicate {kind} token in skeleton: {found}")
    expanded = {
        "law-index": wrap_index([f"`{t}`" for t in tokens["LAW"]]),
        "framing-index": wrap_index([f"`[FRAMING:{t}]`" for t in tokens["FRAMING"]]),
        "generated-notice": [NOTICE],
    }

    out: list[str] = []
    for line, where in assembled:
        d = directive(line, where)
        if d is None:
            out.append(line)
        elif d[0] == "include":
            raise SourceError(f"{where}: includes do not nest")
        elif d[0] != "rung":
            out.extend(expanded[d[0]])
    return "".join(out)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if the target is stale")
    parser.add_argument("--source", type=Path, default=SOURCE)
    parser.add_argument("--target", type=Path, default=TARGET)
    args = parser.parse_args(argv)
    try:
        text = render(args.source)
    except SourceError as e:
        print(f"generate: {e}", file=sys.stderr)
        return 2
    if args.check:
        if args.target.read_text() != text:
            print(f"generate: {args.target} is stale against {args.source}; run {Path(__file__).name}", file=sys.stderr)
            return 1
        return 0
    args.target.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
